### PR TITLE
Implement dry-run option in delete map context class

### PR DESCRIPTION
**Pull request by sbesson**
As a preamble of upcoming work on the performance of the map annotation delete command, this PR:

- unifies the constructor of all the `Context` classes to support a `dry_run` boolean keyword, set to `False` by default
- updates the `DeleteMapAnnotationContext` OMERO deletion method to consume the `dry_run` argument
- updates the CLI `metadata populate` command to propagate the `dry-run` argument to the context class

This should allow to use `bin/omero metadata populate --context deletemap --dry-run` to measure a baseline and compare performance metrics for variations of the deletion commands without deleting the actual annotations on the server.

17e3737 updates the integration tests for the map deletion context class to test `ctx.parse()` with and without `--dry-run`

### CODE REVIEW

**Comment by dominikl** [comment]
The code looks fine (as far as I can tell). But testing on test52 gives me a `LockTimeout` (immediately):
```
[dlindner@test52-omeroreadwrite experimentA]$ /opt/omero/server/OMERO.server/bin/omero metadata populate --context deletemap --cfg idr0042-experimentA-bulkmap-config.yml --dry-run Project:402
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
INFO:omero.util.populate_metadata:Total MapAnnotationLinks in ['openmicroscopy.org/omero/bulk_annotations', 'openmicroscopy.org/omero/bulk_annotations/config', 'openmicroscopy.org/mapr/organism']: 4598
Traceback (most recent call last):
  File "/opt/omero/server/OMERO.server/bin/omero", line 130, in <module>
    rv = omero.cli.argv()
  File "/opt/omero/server/OMERO.server/lib/python/omero/cli.py", line 1620, in argv
    cli.invoke(args[1:])
  File "/opt/omero/server/OMERO.server/lib/python/omero/cli.py", line 1095, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/omero/server/OMERO.server/lib/python/omero/cli.py", line 1172, in onecmd
    self.execute(line, previous_args)
  File "/opt/omero/server/OMERO.server/lib/python/omero/cli.py", line 1254, in execute
    args.func(args)
  File "/home/dlindner/omero-metadata/src/omero_cli_metadata.py", line 491, in populate
    ctx.parse()
  File "/home/dlindner/omero-metadata/src/populate_metadata.py", line 1711, in parse
    self.write_to_omero()
  File "/home/dlindner/omero-metadata/src/populate_metadata.py", line 1878, in write_to_omero
    {"%sAnnotationLink" % objtype: batch}, self.loops, self.ms)
  File "/home/dlindner/omero-metadata/src/populate_metadata.py", line 1893, in _write_to_omero_batch
    del_cmd, loops=loops, ms=ms, failontimeout=True)
  File "/opt/omero/server/OMERO.server/lib/python/omero/clients.py", line 899, in submit
    closehandle=True)
  File "/opt/omero/server/OMERO.server/lib/python/omero/clients.py", line 918, in waitOnCmd
    callback.loop(loops, ms)  # Throw LockTimeout
  File "/opt/omero/server/OMERO.server/lib/python/omero/callbacks.py", line 256, in loop
    5000L, int(waited))
omero.LockTimeout: exception ::omero::LockTimeout
{
    serverStackTrace = None
    serverExceptionClass = None
    message = Command unfinished after 0.0 seconds
    backOff = 5000
    seconds = 0
}
```

**Comment by sbesson** [comment]
The error above is known. This is because the default arguments for `populate --context deletemap` do not work. For now, you should be able to test by passing `--wait 100 --batch 100`.

I plan a follow-up PR to fix the default behavior although I could add a commit here if that's preferable.

PS: be careful when testing map annotation deletion against `test52`...

**Comment by dominikl** [comment]
Tested against east-ci, works fine 👍

**Comment by sbesson** [comment]
Thanks, as discussed earlier today, I'll probably open a follow-up PR to fix the default `--wait` time which might completely refactor the `deletemap` context into a `metadata delete` command.

**Pull request merged**
