### PR TITLE
Fix flake8 issue raised following the Rocky Linux 9 image upgrade

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/ome/omero-metadata/actions/runs/7490016877/job/20387910739

I assume the new operating system is pulling a more recent of `flake8` with additional warnings

### CODE REVIEW

**Comment by jburel** [comment]
@sbesson I was working on branch on that upgrade. I have one test failure on my account. You were faster :-)

**Comment by jburel** [comment]
Same failure ``test_deletebulkanns``

**Comment by sbesson** [comment]
I won't have time to look into the other test failure today. Feel free to close this PR in favor of your branch

**Comment by sbesson** [comment]
After additional debugging, the issue comes from the following log statements

```
INFO     omero.util.Resources:__init__.py:657 Starting
INFO     omero.util.Resources:__init__.py:680 Halted
```

i.e. there is no functional regression but it's surprising that these statements would be send to the stdout

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#370](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/370/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/370/consoleText) for more details.
Possible conflicts:
  - PR #55 kkoz 'Prevent users from creating columns with python keyword names'
    - src/omero_metadata/populate.py
  - PR #64 will-moore 'Support images_by_name for Screen and Plate'
    - src/omero_metadata/populate.py
  - PR #79 dominikl 'Remove leading whitespaces from csv'
    - src/omero_metadata/populate.py

--conflicts

**Review by jburel — APPROVED** [review]

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#371](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/371/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/371/consoleText) for more details.
Possible conflicts:
  - PR #55 kkoz 'Prevent users from creating columns with python keyword names'
    - src/omero_metadata/populate.py
  - PR #64 will-moore 'Support images_by_name for Screen and Plate'
    - src/omero_metadata/populate.py
  - PR #79 dominikl 'Remove leading whitespaces from csv'
    - src/omero_metadata/populate.py

--conflicts

**Comment by joshmoore** [comment]
@dominikl @kkoz @will-moore: any opinions on what order these PRs should be merged? From my POV, this one could go in, but then everyone else will need to deal with the conflicts.

**Comment by dominikl** [comment]
I guess I can just close my PR anyway. There was never a conclusion reached what the right behaviour should actually be.

**Comment by jburel** [comment]
Thanks.
So we can merge and tag. 
This should fix the issue with omero-scripts

**Review by jburel — APPROVED** [review]

**Pull request merged**
