### PR TITLE
Package renaming

### PR DESCRIPTION
**Pull request by sbesson**
See also https://github.com/ome/omero-upload/pull/3

Currently, the `omero-metadata` library installs modules under the root namespace. This moves both the `populate.py` library and the `cli.py` classes under an `omero_metadata` package declared in `setup.py`.

The Travis CI configuration is also updated to include the PyPI deployment as for other Python repositories

Proposed tag: `0.4.0`

### CODE REVIEW

**Comment by joshmoore** [comment]
Are you thinking of changing the repo name as well?

**Comment by sbesson** [comment]
I have not thought about changing the repo name. One obvious downside to doing so would be renaming the PyPI project as well.

Re package name, the alternative to the underscore naming would be to use `omero.metadata`. I think @manics gave this a try and encountered issues. Are these captured somewhere public?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-PLUGINS-merge#1](https://ci.openmicroscopy.org/job/OMERO-PLUGINS-merge/1/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-PLUGINS-merge/1/consoleText) for more details.
Possible conflicts:
  - PR #18 manics 'Add roi utils for creating masks'
    - setup.py
  - Upstream changes
    - setup.py

--conflicts

**Comment by joshmoore** [comment]
Green. Merging then tagging.

**Pull request merged**
