### PR TITLE
Add Image IDs workflow to README

### PR DESCRIPTION
**Pull request by will-moore**
Moved REAMDE updates from #62 to a new PR since they were unrelated to the other changes there.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1011](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1011/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1011/consoleText) for more details.
Possible conflicts:
  - PR #62 will-moore 'Support ROI table on Dataset, for table with ROI ID column'
    - README.rst

--conflicts

**Comment by sbesson** [comment]
The conversation in https://github.com/ome/omero-metadata/pull/62 makes me wonder if we can work on a concise representation of the level of support that would supplement the verbose paragraphs for each scenario. My understanding is that there are two points leading to confusion:

- the level of support for target vs column type (see https://github.com/ome/omero-metadata/issues/65, https://github.com/ome/omero-metadata/issues/51, https://github.com/ome/omero-metadata/issues/25, https://github.com/ome/omero-metadata/pull/62, https://github.com/ome/omero-metadata/pull/64). Is it possible to construct a table showing the different combinations?
- the command behavior if a n object cannot be resolved. My understanding is that the outcomes are: 1- error, 2- add an entry with `-1`, 3- ignore.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1012](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1012/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1012/consoleText) for more details.
Possible conflicts:
  - PR #62 will-moore 'Support ROI table on Dataset, for table with ROI ID column'
    - README.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1013](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1013/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1013/consoleText) for more details.
Possible conflicts:
  - PR #62 will-moore 'Support ROI table on Dataset, for table with ROI ID column'
    - README.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1176](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1176/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1176/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - README.rst

--conflicts

**Pull request closed without merging**
